language: node_js
node_js:
  - "node"
  - "10"
env:
  global:
    - NODE_ENV=development
before_install:
   - pip install --user codecov
install:
  - npm install
script:
  - npm test
after_success: 
   - codecov --file coverage/lcov.info --disable search

 