name: NodeJS CI
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:  [16.x, 17.x]
          
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    # - run: npm run test

  coverage:
    name: Coveralls
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:  [16.x, 17.x]
          
    steps:
    - uses: actions/checkout@v2
      env:
        DBURL: ${{ secrets.DBURL }}
        SECRET: ${{ secrets.SECRET }}
        EMAIL: ${{ secrets.EMAIL }}
        PASSWORD: ${{ secrets.PASSWORD }}
        USERNAME: ${{ secrets.USERNAME }}
      # with:
      #   github-token: ${{ secrets.GITHUB_TOKEN }}
